# Run devtools::document()
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'R/**'
name: call-update-roxygen-docs
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/update-roxygen-docs.yml@main
